### ISSUE TITLE
Scope for Snyk

### ISSUE THREAD

**Issue by dadinolfi** [distributedweaknessfiling/DWF-CNA-Registry#9]
The scope for Snyk, a new CNA, is "All Open Source", which overlaps other CNAs. This should be updated to "All Open Source not covered by another CNA". 

Also, how is Snyk's scope different from the DWF's scope, which is also "All Open Source not covered by another CNA"?

**Comment by kurtseifried** [comment]
Closing out for completeness. We have multiple entities with scope of "All open source" alreadt (Red Hat, DWF, Debian, etc.) so this is nothing new.
